# Generated by Django 2.2.5 on 2019-09-13 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akpsi_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('brother_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='akpsi_core.Member')),
            ],
        ),
    ]
