# Generated by Django 2.2.5 on 2019-09-13 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_number', models.IntegerField(db_column='areaNo', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'ordering': ['area_number'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapter_name', models.CharField(db_column='chapterName', max_length=20, primary_key=True, serialize=False)),
                ('charter_date', models.DateField(blank=True, db_column='charterDate', null=True)),
                ('recharter_date', models.DateField(blank=True, db_column='recharterDate', null=True)),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'ordering': ['chapter_name'],
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('major', models.CharField(db_column='major', max_length=50, primary_key=True, serialize=False)),
                ('college', models.CharField(db_column='college', max_length=50)),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
                'ordering': ['college', 'major'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_code', models.CharField(db_column='memCode', max_length=8, primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='fName', max_length=255)),
                ('middle_name', models.CharField(blank=True, db_column='mName', max_length=255, null=True)),
                ('last_name', models.CharField(db_column='lName', max_length=255)),
                ('nickname', models.CharField(blank=True, db_column='nickname', max_length=255, null=True)),
                ('akpsi_status', models.CharField(choices=[('Collegiate', 'Collegiate'), ('Alumnus', 'Alumnus'), ('LOA-Military', 'Leave of Absense - Military Leave'), ('LOA-Medical', 'Leave of Absense - Medical Leave'), ('LOA-Hardship', 'Leave of Absense - Extreme Hardship'), ('LOA-Abroad', 'Leave of Absense - Study Abroad'), ('Pledge', 'Pledge'), ('Suspended', 'Suspended'), ('Faculty', 'Faculty Brother'), ('Honorary', 'Honorary Brother')], db_column='akpsi_status', max_length=255)),
                ('chapter_status', models.CharField(blank=True, db_column='chapter_status', max_length=255, null=True)),
                ('email1', models.CharField(blank=True, db_column='email1', max_length=255, null=True)),
                ('email2', models.CharField(blank=True, db_column='email2', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=15, null=True)),
                ('pledge_classification', models.CharField(blank=True, db_column='pledgeClass', max_length=40, null=True)),
                ('birthday', models.DateField(blank=True, db_column='birthday', null=True)),
                ('gender', models.CharField(blank=True, db_column='gender', max_length=1, null=True)),
                ('dietary_restrictions', models.CharField(blank=True, db_column='dietRestrict', max_length=255, null=True)),
                ('home_city', models.CharField(blank=True, db_column='homeCity', max_length=100, null=True)),
                ('home_state', models.CharField(blank=True, db_column='homeState', max_length=100, null=True)),
                ('home_country', models.CharField(blank=True, db_column='homeCountry', max_length=100, null=True)),
                ('graduate_program', models.CharField(blank=True, db_column='gradProgram', max_length=50, null=True)),
                ('work_company', models.CharField(blank=True, db_column='workCompany', max_length=100, null=True)),
                ('work_city', models.CharField(blank=True, db_column='workCity', max_length=100, null=True)),
                ('work_state', models.CharField(blank=True, db_column='workState', max_length=100, null=True)),
                ('work_country', models.CharField(blank=True, db_column='workCountry', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('chapter', models.ForeignKey(blank=True, db_column='chapter', null=True, on_delete=django.db.models.deletion.SET_NULL, to='akpsi_core.Chapter')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['chapter', 'akpsi_status', 'chapter_status', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_code', models.CharField(db_column='semCode', max_length=5, primary_key=True, serialize=False)),
                ('semester_term', models.CharField(db_column='semTerm', max_length=6)),
                ('semester_year', models.IntegerField(db_column='semYear')),
                ('semester_induction', models.DateField(blank=True, db_column='semInduction', null=True)),
                ('semester_initiation', models.DateField(blank=True, db_column='semInitiation', null=True)),
                ('beginning_actives', models.IntegerField(blank=True, db_column='beginningActives', null=True)),
                ('applications', models.IntegerField(blank=True, db_column='applications', null=True)),
                ('prospect_interviews', models.IntegerField(blank=True, db_column='prospectInterviews', null=True)),
                ('bids_extended', models.IntegerField(blank=True, db_column='bidsExtended', null=True)),
                ('pledges_pinned', models.IntegerField(blank=True, db_column='pledgesPinned', null=True)),
                ('brothers_initiated', models.IntegerField(blank=True, db_column='brothersInitiated', null=True)),
                ('sponsorships', models.IntegerField(blank=True, db_column='sponsorships', null=True)),
                ('fundraising', models.IntegerField(blank=True, db_column='fundraising', null=True)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ['semester_year', '-semester_term'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_name', models.CharField(db_column='uniName', max_length=255, primary_key=True, serialize=False)),
                ('university_city', models.CharField(blank=True, db_column='uniCity', max_length=100, null=True)),
                ('university_state', models.CharField(blank=True, db_column='uniState', max_length=100, null=True)),
                ('university_country', models.CharField(blank=True, db_column='uniCountry', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'ordering': ['university_name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_name', models.CharField(db_column='regionName', max_length=50, primary_key=True, serialize=False)),
                ('area_number', models.ForeignKey(blank=True, db_column='areaNo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='akpsi_core.Area')),
                ('regional_director', models.ForeignKey(blank=True, db_column='rd', null=True, on_delete=django.db.models.deletion.SET_NULL, to='akpsi_core.Member')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='graduate_semester',
            field=models.ForeignKey(blank=True, db_column='gradSem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grad_semester', to='akpsi_core.Semester'),
        ),
        migrations.AddField(
            model_name='member',
            name='graduate_university',
            field=models.ForeignKey(blank=True, db_column='gradUni', null=True, on_delete=django.db.models.deletion.SET_NULL, to='akpsi_core.University'),
        ),
        migrations.AddField(
            model_name='member',
            name='major',
            field=models.ForeignKey(blank=True, db_column='major', null=True, on_delete=django.db.models.deletion.SET_NULL, to='akpsi_core.College'),
        ),
        migrations.AddField(
            model_name='member',
            name='pledge_semester',
            field=models.ForeignKey(blank=True, db_column='pledgeSem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledge_semester', to='akpsi_core.Semester'),
        ),
        migrations.AddField(
            model_name='member',
            name='reinstate_semester',
            field=models.ForeignKey(blank=True, db_column='reinstateSem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinstatement_semester', to='akpsi_core.Semester'),
        ),
        migrations.AddField(
            model_name='member',
            name='suspension_semester',
            field=models.ForeignKey(blank=True, db_column='susSem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspension_semester', to='akpsi_core.Semester'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_university',
            field=models.ForeignKey(db_column='chapterUni', on_delete=django.db.models.deletion.CASCADE, to='akpsi_core.University'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='region_name',
            field=models.ForeignKey(blank=True, db_column='region', null=True, on_delete=django.db.models.deletion.SET_NULL, to='akpsi_core.Region'),
        ),
        migrations.AddField(
            model_name='area',
            name='area_vp',
            field=models.ForeignKey(blank=True, db_column='areaVP', null=True, on_delete=django.db.models.deletion.SET_NULL, to='akpsi_core.Member'),
        ),
    ]
